val = ['“Nothing is true, everything is permitted.” – Assassin’s Creed franchise', '"All we had to do was follow the damn train, CJ" – Big Smoke', '“You were almost a Jill sandwich!” – Resident Evil', '“It’s a-me, Mario!” – Assassin’s Creed II', '“FINISH HIM!” – Mortal Kombat', 'Playing Second match with the same clan team - "Oh Clan Match aa idu" – vijay vegnesh','"semma da" – vijay vegnesh', '"na irunda enna ilana enna" – vijay vegnesh', '"Enda ellarum enna matum idikiringa" – nurburg_10','"tribute to DD" – nurburg_10','"Your centre is your opponent\'s centre – nurburg_10" ', '"miss panten" – nurburg_10', '"dei adu poirukanum da" – nurburg_10', '"en ne sollu" – nurburg_10', '"en ne po" – nurburg_10', '"seri na othukuren na pro than" – ソル・インヴィクタス', '"fck" – ThatAin\'tMe', '"na illa adu" – Chan', '"na than na than" – Chan', '"oru goal aavadu podanum" – Chan', '"m hiding n playing" – IIIIIIIII_13', '"i cant talk tho" – IIIIIIIII_13', '"Mom shouting da" – IIIIIIIII_13', '"ennaku aada theriyadhu" – Phantom ニトロー', '"Im gonna vibe" – Phantom ニトロー', '"..." – Phantom ニトロー', '"dei apdi laam onnum illa da" – † sao †','"Vj von vaai iruke" – † sao †', '"engeyo poiduchu" – Kaipulla24', '"enna nadakudu nu purila" – Kaipulla24', '"inum ore oru match aaduvom" – Kaipulla24', '"moonu perum ponanunga moonu perum vittanga seri apo goal than" – Vageesan', '"hey ada paavi" – Vageesan', '"avan viduvan nu ethirpakala" – Vageesan' ]
valnew = ['"lalapettai giri giri aaya sutta vadakari"', '"Aandavan soluran arunachalam mudikuran"', '"+1/0"']
gamequote = ['“Kept you waiting, huh?” — Metal Gear Solid 5: Ground Zeroes', '“You Have Died” – Dark Souls', '“Frostmourne hungers” – WarCraft III', '“You require more vespene gas” and “Not Enough Minerals” – StarCraft', '“The cake is a lie” – Portal', '“I don’t need a weapon; my friends are my power!” – Kingdom Hearts', '“[silence]” – The Legend of Zelda', '“Waka Waka Waka” – Pacman', '“Had to be me… Someone else might have got it wrong.” – Mass Effect 3', '“War has changed” – Metal Gear Solid IV', '“Love is just a chemical. We give it meaning by choice.” – Bioshock 2', '“It ain’t no secret I didn’t get these scars falling over in church.” – Red Dead Redemption', '“DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM” – Fallout 3', '“A hero need not speak. When he is gone, the world will speak for him” – Halo', '“Did I ever tell you the definition of insanity?” – Far Cry 3', '“Stand in the ashes of a trillion dead souls and ask the ghosts if honor matters. Their silence is your answer.” – Mass Effect 3', 'Batman: “You want to know something funny? Even after everything you’ve done, I would have saved you.” The Joker: [laughs, coughs] “that is pretty funny.” – Batman: Arkham City', '“The truth, Walker, is that you’re here because you wanted to feel like something you’re not: A hero.” – Spec Ops: The Line', '“You’ve met with a terrible fate, haven’t you?” – The Legend of Zelda: Majora’s Mask', '“Are you a bad enough dude to rescue the president?” – Bad Dudes', '“Good! Now we can fight as warriors. Hand-to-hand, it is the basis of all combat. Only a fool trusts his life to a weapon.” – Metal Gear Solid', '“Someday you’re bound to lose everything. Everybody around you will be gone.” – Final Fantasy VIII', '“What is bravery, without a dash of recklessness?” – Dark Souls', '“A famous explorer once said that the extraordinary is in what we do, not who we are.” – Tomb Raider', '“The only thing that can defeat power, is more power.” – Resident Evil: Umbrella Chronicles', '“No matter how dark the night, the morning always comes.” – Final Fantasy X', '“What is a man but the sum of his memories? We are the stories we live, the tales we tell ourselves.” – Assassin’s Creed: Revelations']
valone = val + valnew
valfinal =  valone + gamequote
egg = ["`Do you know Hal 9000`", "`Do you know Siri`", "`Are you real`", "`Use the Force`", "`Do you speak Morse Code`", "`do you watch Rick and Morty`"]



#https://www.gamedesigning.org/gaming/video-game-quotes/
#https://www.gamesradar.com/best-video-game-quotes-all-time/
#val = ['“Nothing is true, everything is permitted.” – Assassin’s Creed franchise', '"All we had to do was follow the damn train, CJ" – Big Smoke', '“You were almost a Jill sandwich!” – Resident Evil', '“It’s a-me, Mario!” – Assassin’s Creed II', '“FINISH HIM!” – Mortal Kombat', 'Playing Second match with the same clan team - "Oh Clan Match aa idu" – <@428446161393942529>','"semma da" – <@428446161393942529>', '"na irunda enna ilana enna" – <@428446161393942529>', '"Enda ellarum enna matum idikiringa" – <@427902008620744724>','"tribute to DD" – <@427902008620744724>','"Your centre is your opponent\'s centre – <@427902008620744724>" ', '"miss panten" – <@427902008620744724>', '"dei adu poirukanum da" – <@427902008620744724>', '"en ne sollu" – <@427902008620744724>', '"en ne po" – <@427902008620744724>', '"seri na othukuren na pro than" – <@701851249947181215>', '"fck" – <@609028600305287169>', '"na illa adu" – <@767632288309182464>', '"na than na than" – <@767632288309182464>', '"oru goal aavadu podanum" – <@767632288309182464>', '"m hiding n playing" – <@483140736213188632>', '"i cant talk tho" – <@483140736213188632>', '"Mom shouting da" – <@483140736213188632>', '"ennaku aada theriyadhu" – <@730786089857450005>', '"Im gonna vibe" – <@730786089857450005>', '"..." – <@730786089857450005>', '"dei apdi laam onnum illa da" – <@752088286746509363>','"Vj von vaai iruke" – <@752088286746509363>', '"engeyo poiduchu" – <@759396033045200896>', '"enna nadakudu nu purila" – <@759396033045200896>', '"inum ore oru match aaduvom" – <@759396033045200896>', '"moonu perum ponanunga moonu perum vittanga seri apo goal than" – <@736474202068222033>', '"hey ada paavi" – <@736474202068222033>', '"avan viduvan nu ethirpakala" – <@736474202068222033>' ]
